"""add_phone_index_to_users

Revision ID: 11e19fff40b9
Revises: 79f1c6b6f0f8
Create Date: 2026-04-22 01:46:00.853562

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "11e19fff40b9"
down_revision: Union[str, Sequence[str], None] = "79f1c6b6f0f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    # ### end Alembic commands ###
