"""add_store_config_fields

Revision ID: 3874b3bbeb5e
Revises: 11e19fff40b9
Create Date: 2026-04-22 14:18:54.862717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3874b3bbeb5e"
down_revision: Union[str, Sequence[str], None] = "11e19fff40b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("buffer_minutes", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "stores",
        sa.Column("business_hours", sa.JSON(), nullable=False, server_default="{}"),
    )
    op.add_column(
        "stores",
        sa.Column(
            "send_email_confirmation",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    op.add_column(
        "stores",
        sa.Column(
            "send_email_reminders", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "send_email_reminders")
    op.drop_column("stores", "send_email_confirmation")
    op.drop_column("stores", "business_hours")
    op.drop_column("stores", "buffer_minutes")
    # ### end Alembic commands ###
