"""add_min_booking_notice_hours

Revision ID: 5356b5f06629
Revises: 557c4ce4c410
Create Date: 2026-05-02 22:27:46.409268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5356b5f06629'
down_revision: Union[str, Sequence[str], None] = '557c4ce4c410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('min_booking_notice_hours', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'min_booking_notice_hours')
    # ### end Alembic commands ###
