"""Normalize DB to 3NF

Revision ID: 557c4ce4c410
Revises: 3874b3bbeb5e
Create Date: 2026-05-02 18:44:52.412997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '557c4ce4c410'
down_revision: Union[str, Sequence[str], None] = '3874b3bbeb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_schedules',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_schedules_public_id'), 'store_schedules', ['public_id'], unique=True)
    op.create_index(op.f('ix_store_schedules_store_id'), 'store_schedules', ['store_id'], unique=False)
    op.drop_column('appointments', 'ends_at')
    op.drop_column('budgets', 'total_cost')
    op.drop_column('stores', 'business_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('business_hours', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
    op.add_column('budgets', sa.Column('total_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_store_schedules_store_id'), table_name='store_schedules')
    op.drop_index(op.f('ix_store_schedules_public_id'), table_name='store_schedules')
    op.drop_table('store_schedules')
    # ### end Alembic commands ###
