"""add_absent_status_and_appointment_fields

Revision ID: 79f1c6b6f0f8
Revises: 86384cd34416
Create Date: 2026-04-22 01:35:43.607117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79f1c6b6f0f8"
down_revision: Union[str, Sequence[str], None] = "86384cd34416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("notes_staff", sa.Text(), nullable=True))
    op.add_column(
        "appointments", sa.Column("cancelled_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "appointments", sa.Column("completed_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "appointments",
        "notes",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_appointments_status"), "appointments", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.alter_column(
        "appointments",
        "notes",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.drop_column("appointments", "completed_at")
    op.drop_column("appointments", "cancelled_at")
    op.drop_column("appointments", "notes_staff")
    # ### end Alembic commands ###
