"""add_audit_logs_and_staff_blocks

Revision ID: 86384cd34416
Revises: e1a7b9c2d4f0
Create Date: 2026-04-21 02:28:10.210258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86384cd34416"
down_revision: Union[str, Sequence[str], None] = "e1a7b9c2d4f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_public_id", sa.String(length=26), nullable=True),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=26), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("payload_before", sa.JSON(), nullable=True),
        sa.Column("payload_after", sa.JSON(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "staff_blocks",
        sa.Column("store_id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staff_blocks_public_id"), "staff_blocks", ["public_id"], unique=True
    )
    op.create_index(
        op.f("ix_staff_blocks_staff_id"), "staff_blocks", ["staff_id"], unique=False
    )
    op.create_index(
        op.f("ix_staff_blocks_starts_at"), "staff_blocks", ["starts_at"], unique=False
    )
    op.create_index(
        op.f("ix_staff_blocks_store_id"), "staff_blocks", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_staff_blocks_store_id"), table_name="staff_blocks")
    op.drop_index(op.f("ix_staff_blocks_starts_at"), table_name="staff_blocks")
    op.drop_index(op.f("ix_staff_blocks_staff_id"), table_name="staff_blocks")
    op.drop_index(op.f("ix_staff_blocks_public_id"), table_name="staff_blocks")
    op.drop_table("staff_blocks")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
