"""add_service_youtube_url

Revision ID: b4d5483bfcee
Revises: 5356b5f06629
Create Date: 2026-05-04 19:26:09.868928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4d5483bfcee"
down_revision: Union[str, Sequence[str], None] = "5356b5f06629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column("youtube_trailer_url", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "youtube_trailer_url")
    # ### end Alembic commands ###
