"""refactor_backend_v2_fix

Revision ID: c5d8226c1b3e
Revises: d5ec116d06a3
Create Date: 2026-05-15 16:57:37.924516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c5d8226c1b3e"
down_revision: Union[str, Sequence[str], None] = "d5ec116d06a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_constraint(
        op.f("uq_staff_appointment_time"), "appointments", type_="unique"
    )
    op.create_index(op.f("ix_appointments_id"), "appointments", ["id"], unique=False)
    op.create_foreign_key(None, "audit_logs", "users", ["actor_id"], ["id"])
    op.alter_column(
        "budgets",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_budgets_public_id"), table_name="budgets")
    op.create_foreign_key(None, "budgets", "stores", ["store_id"], ["id"])
    op.drop_column("budgets", "public_id")
    op.alter_column(
        "schedules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_staff_day_schedule"), "schedules", type_="unique")
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_foreign_key(None, "schedules", "staff", ["staff_id"], ["id"])
    op.alter_column(
        "services",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "services", "stores", ["store_id"], ["id"])
    op.drop_constraint(op.f("staff_user_id_key"), "staff", type_="unique")
    op.create_index(op.f("ix_staff_email"), "staff", ["email"], unique=False)
    op.create_index(op.f("ix_staff_id"), "staff", ["id"], unique=False)
    op.drop_column("staff", "user_id")
    op.create_foreign_key(
        None, "staff_services", "services", ["service_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "staff_services", "staff", ["staff_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "store_schedules",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_schedules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "store_schedules",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_store_schedules_public_id"), table_name="store_schedules")
    op.create_foreign_key(None, "store_schedules", "stores", ["store_id"], ["id"])
    op.drop_column("store_schedules", "public_id")
    op.alter_column(
        "stores",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "stores",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=50), nullable=True))
    op.alter_column("users", "store_id", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_store_id"), "users", ["store_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_store_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column("users", "store_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "phone")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "hashed_password")
    op.alter_column(
        "stores",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "stores",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "store_schedules",
        sa.Column(
            "public_id", sa.VARCHAR(length=26), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "store_schedules_store_id_fkey", "store_schedules", type_="foreignkey"
    )
    op.create_index(
        op.f("ix_store_schedules_public_id"),
        "store_schedules",
        ["public_id"],
        unique=True,
    )
    op.alter_column(
        "store_schedules",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "store_schedules",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "store_schedules",
        "id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_constraint(
        "staff_services_staff_id_fkey", "staff_services", type_="foreignkey"
    )
    op.drop_constraint(
        "staff_services_service_id_fkey", "staff_services", type_="foreignkey"
    )
    op.add_column(
        "staff", sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_staff_id"), table_name="staff")
    op.drop_index(op.f("ix_staff_email"), table_name="staff")
    op.create_unique_constraint(
        op.f("staff_user_id_key"),
        "staff",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("services_store_id_fkey", "services", type_="foreignkey")
    op.alter_column(
        "services",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_constraint("schedules_staff_id_fkey", "schedules", type_="foreignkey")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.create_unique_constraint(
        op.f("uq_staff_day_schedule"),
        "schedules",
        ["staff_id", "day_of_week"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "schedules",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "budgets",
        sa.Column(
            "public_id", sa.VARCHAR(length=26), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("budgets_store_id_fkey", "budgets", type_="foreignkey")
    op.create_index(op.f("ix_budgets_public_id"), "budgets", ["public_id"], unique=True)
    op.alter_column(
        "budgets",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_constraint("audit_logs_actor_id_fkey", "audit_logs", type_="foreignkey")
    op.drop_index(op.f("ix_appointments_id"), table_name="appointments")
    op.create_unique_constraint(
        op.f("uq_staff_appointment_time"),
        "appointments",
        ["staff_id", "starts_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_appointments_status"), "appointments", ["status"], unique=False
    )
    # ### end Alembic commands ###
